package subsystem

// the only job of this package is to import all subsystem packages so they're actually registered
// Call Register() from main() instead of blank-importing this package.

import (
	_ "elichika/internal/subsystem/banner"
	_ "elichika/internal/subsystem/cache"
	_ "elichika/internal/subsystem/pickup_info"
	_ "elichika/internal/subsystem/reset_progress"
	_ "elichika/internal/subsystem/time"
	_ "elichika/internal/subsystem/user_accessory"
	_ "elichika/internal/subsystem/user_account"
	_ "elichika/internal/subsystem/user_authentication"
	_ "elichika/internal/subsystem/user_beginner_challenge"
	_ "elichika/internal/subsystem/user_bootstrap"
	_ "elichika/internal/subsystem/user_card"
	_ "elichika/internal/subsystem/user_content"
	_ "elichika/internal/subsystem/user_custom_background"
	_ "elichika/internal/subsystem/user_daily_theater"
	_ "elichika/internal/subsystem/user_emblem"
	_ "elichika/internal/subsystem/user_event"
	_ "elichika/internal/subsystem/user_expired_item"
	_ "elichika/internal/subsystem/user_gacha"
	_ "elichika/internal/subsystem/user_gps_present"
	_ "elichika/internal/subsystem/user_info_trigger"
	_ "elichika/internal/subsystem/user_lesson"
	_ "elichika/internal/subsystem/user_lesson_deck"
	_ "elichika/internal/subsystem/user_live"
	_ "elichika/internal/subsystem/user_live_deck"
	_ "elichika/internal/subsystem/user_live_difficulty"
	_ "elichika/internal/subsystem/user_live_mv"
	_ "elichika/internal/subsystem/user_live_party"
	_ "elichika/internal/subsystem/user_login"
	_ "elichika/internal/subsystem/user_login_bonus"
	_ "elichika/internal/subsystem/user_love_ranking"
	_ "elichika/internal/subsystem/user_member"
	_ "elichika/internal/subsystem/user_member_guild"
	_ "elichika/internal/subsystem/user_mission"
	_ "elichika/internal/subsystem/user_new_badge"
	_ "elichika/internal/subsystem/user_play_list"
	_ "elichika/internal/subsystem/user_present"
	_ "elichika/internal/subsystem/user_profile"
	_ "elichika/internal/subsystem/user_reference_book"
	_ "elichika/internal/subsystem/user_review_request_process_flow"
	_ "elichika/internal/subsystem/user_rule_description"
	_ "elichika/internal/subsystem/user_scene_tips"
	_ "elichika/internal/subsystem/user_sif_2_data_link"
	_ "elichika/internal/subsystem/user_sifid_reward_mission"
	_ "elichika/internal/subsystem/user_social"
	_ "elichika/internal/subsystem/user_status"
	_ "elichika/internal/subsystem/user_steady_voltage_ranking"
	_ "elichika/internal/subsystem/user_story_event_history"
	_ "elichika/internal/subsystem/user_story_linkage"
	_ "elichika/internal/subsystem/user_story_main"
	_ "elichika/internal/subsystem/user_story_member"
	_ "elichika/internal/subsystem/user_story_side"
	_ "elichika/internal/subsystem/user_subscription_status"
	_ "elichika/internal/subsystem/user_suit"
	_ "elichika/internal/subsystem/user_tower"
	_ "elichika/internal/subsystem/user_trade"
	_ "elichika/internal/subsystem/user_training_tree"
	_ "elichika/internal/subsystem/user_tutorial"
	_ "elichika/internal/subsystem/user_unlock_scene"
	_ "elichika/internal/subsystem/user_voice"
	_ "elichika/internal/subsystem/voltage_ranking"
)

// Register triggers all subsystem registrations by importing this package.
func Register() {}
